---
title: "DetNut_MassLoss"
author: "CJR"
date: "12/26/2021"
output: html_document
---
The purpose of this analysis is to test 1) assumptions about the log-linearity of mass loss during stream detrital decomposition, and 2) How intrinsic and extrinsic factors influence the functional form of litter breakdown through time

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(gratia)
library(mgcv)
library(tidymv)

```

```{r data ingest}


det_raw <- read_csv("C:\\Users\\robbi\\Dropbox\\Detrital Nutrients Synth\\DetNutSynth_Database.csv")

det_ml <- det_loc%>%filter(Meas_Day <=100)%>%mutate(Mass_prop_remaining = Mass_per_remaining/100)

det_ml2 <- det_loc%>%filter(Meas_Day <=100, Mass_per_remaining<100)%>%mutate(Mass_prop_remaining = Mass_per_remaining/100)

```

```{r}

ml_1 <- gam(data = det_ml, Mass_prop_remaining ~
              te(Meas_Day, Temperature_C, initial_N, m = 2)+
              s(series_index, Meas_Day, bs = "re"), 
            method = "REML", family = betar(link = "logit"), select = TRUE)


ml_2 <- gam(data = det_ml, Mass_prop_remaining ~
              te(Meas_Day, Temperature_C, m = 2)+
              s(series_index, Meas_Day, bs = "re"), 
            method = "REML", family = betar(link = "logit"), select = TRUE)

ml_2a <- gam(data = det_ml2, Mass_prop_remaining ~
              te(Meas_Day, Temperature_C, m = 2)+
               s(series_index, bs = "re")+s(series_index, Meas_Day, bs = "re"), 
            method = "REML", family = betar(link = "logit"), select = TRUE)

```

```{r}
ml_T.pred<-predict_gam(type = "link", ml_1, length_out = 5000,  exclude_terms = c("s(series_index)", "s(series_index, Meas_Day)"), values = list(series_index = NULL,Remain_Mass_Category = NULL, initial_N = c(0.4,1.0,1.5,2.0),Temperature_C = c(5,10,15,20)))%>%
   mutate(Temperature_C = as_factor(Temperature_C), initial_N = as_factor(initial_N))
  


 ml_T.p <- ggplot()+
    geom_smooth(data = ml_T.pred, se = FALSE, aes(x = Meas_Day, y = 1/(1+exp(-fit)), color = initial_N, linetype = Temperature_C))+
   facet_grid(initial_N~Temperature_C)+
   geom_ribbon(data = ml_T.pred, aes(x = Meas_Day, ymin = 1/(exp(-(fit - 2*se.fit))), ymax = 1/(exp(-(fit + 2*se.fit))), alpha = 0.3))+
   scale_y_continuous(limits =c(0,1))+
    geom_abline(slope = -0.01, intercept = 1)+
    NULL
 ml_T.p

```

```{r}
ml2_T.pred<-predict_gam(type = "link", ml_2a, length_out = 5000,  exclude_terms = c("s(series_index)", "s(series_index, Meas_Day)"), values = list(series_index = NULL,Remain_Mass_Category = NULL,Temperature_C = c(5,10,15,20)))%>%
   mutate(Temperature_C = as_factor(Temperature_C))
  


 ml2_T.p <- ggplot()+
    geom_smooth(data = ml2_T.pred, se = FALSE, aes(x = Meas_Day, y = 1/(1+exp(-fit)), linetype = Temperature_C))+
   facet_grid(.~Temperature_C)+
   geom_ribbon(data = ml2_T.pred, aes(x = Meas_Day, ymin = 1/(exp(-(fit - 2*se.fit))), ymax = 1/(exp(-(fit + 2*se.fit))), alpha = 0.3))+
   scale_y_continuous(limits =c(0,1))+
    geom_abline(slope = -0.01, intercept = 1)+
    NULL
 ml2_T.p

```