---
title: "Proofing Development"
author: "CJR"
date: "July 26, 2020"
output: html_document
---
The point of this document is to develop the Detrital Nutrients Proofing Script
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(assertr)

```

```{r Set working directory}
#Use the test directory on the Desktop
DetNut_Files<-list.files("/Users/robbi/Desktop/txt_test", full.names = TRUE) #Obviously change this to where you need to
DetNut_Files

```

```{r Read files}
DetNut<-DetNut_Files%>%
  map(~read_tsv(.x, col_types = cols(First_Author = "c",
                                     Title = "c",
                                     Year = "c",
                                     Journal = "c",
                                     DOI = "c",
                                     System = "c",
                                     Flow_Category = "c",
                                     Decay_Method = "c",
                                     Mesh_Size_Category = "c",
                                     Setting = "c",
                                     Manipulation = "c",
                                     LULC_Category = "c",
                                     Light_Category = "c",
                                     Detritus_Type = "c",
                                     Detritus_Condition = "c",
                                     Detritus_Species = "c",
                                     Remain_Mass_Category = "c",
                                     Component_Mass_Category = "c",
                                     Geog_Locale = "c",
                                     LULC_Quantified = "c",
                                     Inverts_AddInfo = "c",
                                     Microbes_AddInfo = "c",
                                     CNPFluxes_AddInfo = "c",
                                     Notes = "c",
                                     .default = "n"))
         )

names(DetNut) <- DetNut_Files%>%
  str_remove("/Users/robbi/Desktop/txt_test/")
#convert each element of the list DetNut to a dataframe within the list "DetNut"



DetNut<-DetNut[-c(4,5)]
  

# find a way to trim off rows with all NA


```




```{r}
QA <- vector(mode = "list", length = length(DetNut))

proofing_chain<-.%>%#this will be a way to store all of our assertions. For now, just keeping at two unrealistic assertions provides the challenge needed to correctly code writing multiple sets of assertion errors for each paper because each assertion writes its own list at least the way this is looped currently
  chain_start%>%
 assert(within_bounds(0,5),Meas_Day)%>%
  assert(within_bounds(0,1),CN_molar)%>%
    chain_end(error_fun = error_append)
  
#
err <- vector(mode = "list", length = length(functions(check_me))-2) #make err a list within QA? Doesn't work as is.

for(i in 1:length(DetNut)) {
QA[[i]] <-  DetNut[[i]]%>%
  proofing_chain%>%
  attr("assertr_errors")

 
}


names(QA)<-names(DetNut)
#Should be able to just pull the error_df dataframe and then slap that end to end into a larger dataframe for each paper/list, somehow...

```

for(i in 1:length(QA)) {
names(QA[[i]])<-c(paste(names(QA[i]),"Errors"), paste(names(QA[i]),"Data"))

for (i in 1:length(QA)) {
  QA[[i]][[2]] <- DetNut[[i]]
}


}
```


  