---
title: "DetNut_GAM_Sensitivity"
author: "CJR"
date: "2022-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)



library(broom)
library(tidymv)
library(tidyverse)
library(mgcv)
library(gratia)
library(cowplot)
library(doSNOW)
library(here)

here::i_am("Stream DetNuts Paper/GAM_Series_Sensitivity.Rmd")

#load analysis data
load(here("Tidy Data and Summarize/DetNut_Data_for_Analysis.Rdata"))
```

#N mass base model
```{r}

series_remove <- det_loc|>filter(!is.na(N_mass_norm)&!is.na(initial_N))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()
series_remove <- series_remove[1:10]

cl <- parallel::makeCluster(4)
registerDoSNOW(cl)
iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc|>filter(series_index != remove.i)
  gam.i_preds <-  gam(data = data.i, N_mass_norm ~  
                     te(Mass_per_loss, initial_N, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "REML", family = Gamma(link = "inverse"),select = TRUE) 
  

predict_gam(type = "link", gam.i_preds, length_out = 1000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL, initial_N = c(3,2,1.5,1.0,0.6,0.3)))%>%
  mutate(initial_N = as_factor(initial_N))|>
  select(-series_index)|>
  mutate(index = as_factor(i), series_index = as_factor(remove.i))

#print(paste("Completed iteration", i), sep = " ")
}

#loop for predictions
registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc|>filter(series_index != remove.i)
   gam.i_pval <-  gam(data = data.i, N_mass_norm ~  
               ti(Mass_per_loss, m = 2) + ti(initial_N, m = 2)+
                     ti(Mass_per_loss, initial_N, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "ML", family = Gamma(link = "inverse"),select = TRUE)  

tidy(gam.i_pval)|>filter(str_detect(term, "Mass_per_loss,"))|>bind_cols(id.i)
}

Ni_sens.p<- ggplot()+
  geom_line(data = gam_preds, aes(x = Mass_per_loss, group = index, y = 1/fit, color = initial_N), alpha = 0.2)+
    geom_abline(slope = -0.01, intercept = 1)+
  ylab("Normalized N Mass")+
  xlab("Mass Loss (%)")+
  facet_wrap(.~initial_N)+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial N (%)"))+
   theme_bw()+
    NULL
 Ni_sens.p
 


 Ni_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 0.106, color = "red") #base mod p-value

 Nsens_grid<-plot_grid(Ni_sens.p,Ni_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
 
#ggsave2("C:/Users/robbi/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/Ni_sens.pdf", Nsens_grid, width = 7.8, height = 9.1, dpi = 600)
```

# P Mass models
```{r}
#1. create list of time series to delete
series_remove <- det_loc|>filter(!is.na(P_mass_norm)&!is.na(initial_P))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()


cl <- parallel::makeCluster(4)
registerDoSNOW(cl)
iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc|>filter(series_index != remove.i)
  gam.i_preds <-  gam(data = data.i, P_mass_norm ~  
                     te(Mass_per_loss, initial_P, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "REML", family = Gamma(link = "inverse"),select = TRUE) 
  

predict_gam(type = "link", gam.i_preds, length_out = 1000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL, initial_P = c(3,2,1.5,1.0,0.6,0.3)))%>%
  mutate(initial_P = as_factor(initial_P))|>
  select(-series_index)|>
  mutate(index = as_factor(i), series_index = as_factor(remove.i))

#print(paste("Completed iteration", i), sep = " ")
}

#loop for predictions
registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc|>filter(series_index != remove.i)
   gam.i_pval <-  gam(data = data.i, N_mass_norm ~  
               ti(Mass_per_loss, m = 2) + ti(initial_P, m = 2)+
                     ti(Mass_per_loss, initial_P, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "ML", family = Gamma(link = "inverse"),select = TRUE)  

tidy(gam.i_pval)|>filter(str_detect(term, "Mass_per_loss,"))|>bind_cols(id.i)
}


Pi_sens.p<- ggplot()+
  geom_line(data = gam_preds, aes(x = Mass_per_loss, group = model_iteration, y = 1/fit, color = Initial_P), alpha = 0.2)+
    geom_abline(slope = -0.01, intercept = 1)+
  ylab("Normalized P Mass")+
  xlab("Mass Loss (%)")+
  facet_wrap(.~Initial_P)+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial P (%)"))+
   theme_bw()+
    NULL
 Pi_sens.p
 


 Pi_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 0.0012, color = "red") #base mod p-value

 
 Psens_grid<-plot_grid(Pi_sens.p,Pi_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
#ggsave2("C:/Users/robbi/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/Pi_sens.pdf", Psens_grid, width = 7.8, height = 9.1, dpi = 600)
 
```

# CN  models
```{r}
#1. create list of time series to delete
series_remove <- det_loc_cnp|>filter(!is.na(CN_ratio)&!is.na(initial_CN))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()

cl <- parallel::makeCluster(4)
registerDoSNOW(cl)
iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
  gam.i_preds <-  gam(data = data.i, CN_ratio ~  
                     te(Mass_per_loss, initial_CN, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "REML", family = Gamma(link = "inverse"),select = TRUE) 
  

predict_gam(type = "link", gam.i_preds, length_out = 1000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL, initial_CN = c(3,2,1.5,1.0,0.6,0.3)))%>%
  mutate(initial_CN = as_factor(initial_CN))|>
  select(-series_index)|>
  mutate(index = as_factor(i), series_index = as_factor(remove.i))

#print(paste("Completed iteration", i), sep = " ")
}

#loop for predictions
registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
   gam.i_pval <-  gam(data = data.i, CN_ratio ~  
               ti(Mass_per_loss, m = 2) + ti(initial_CN, m = 2)+
                     ti(Mass_per_loss, initial_CN, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "ML", family = Gamma(link = "log"),select = TRUE)  

tidy(gam.i_pval)|>filter(str_detect(term, "Mass_per_loss,"))|>bind_cols(id.i)
}

CNi_sens.p<- ggplot()+
  geom_line(data = gam_preds, aes(x = Mass_per_loss, group = model_iteration, y = exp(fit), color = initial_CN), alpha = 0.2)+
  ylab("C:N Ratio")+
  xlab("Mass Loss (%)")+
  facet_wrap(.~initial_CN, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial CN"))+
   theme_bw()+
    NULL
 CNi_sens.p
 

#pvalue density plot - p-value from base penalized model shown in red

 CNi_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+annotate("text", y = 0.5, x = 0,label = "All P-values evaluated to 0")#+geom_vline(xintercept = 2e-16, color = "red") #base mod p-value
 
 CNsens_grid<-plot_grid(CNi_sens.p,CNi_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
#ggsave2("C:/Users/robbi/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/CNi_sens.pdf", CNsens_grid, width = 7.8, height = 9.1, dpi = 600)
```

# CP  models
```{r}
#1. create list of time series to delete
series_remove <- det_loc_cnp|>filter(!is.na(CP_ratio)&!is.na(initial_CP))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()

cl <- parallel::makeCluster(4)
registerDoSNOW(cl)
iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
  gam.i_preds <-  gam(data = data.i, CP_ratio ~  
                     te(Mass_per_loss, initial_CP, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "REML", family = Gamma(link = "inverse"),select = TRUE) 
  

predict_gam(type = "link", gam.i_preds, length_out = 1000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL, initial_CP = c(3,2,1.5,1.0,0.6,0.3)))%>%
  mutate(initial_CP = as_factor(initial_CP))|>
  select(-series_index)|>
  mutate(index = as_factor(i), series_index = as_factor(remove.i))

#print(paste("Completed iteration", i), sep = " ")
}

#loop for predictions
registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
   gam.i_pval <-  gam(data = data.i, CP_ratio ~  
               ti(Mass_per_loss, m = 2) + ti(initial_CP, m = 2)+
                     ti(Mass_per_loss, initial_CP, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "ML", family = Gamma(link = "log"),select = TRUE)  

tidy(gam.i_pval)|>filter(str_detect(term, "Mass_per_loss,"))|>bind_cols(id.i)
}

CPi_sens.p<- ggplot()+
  geom_line(data = gam_preds, aes(x = Mass_per_loss, group = model_iteration, y = exp(fit), color = initial_CP), alpha = 0.2)+
  ylab("C:P Ratio")+
  xlab("Mass Loss (%)")+
  facet_wrap(.~initial_CP, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial CP"))+
   theme_bw()+
    NULL
 CPi_sens.p
 

#pvalue density plot - p-value from base penalized model shown in red

 CPi_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 0.0003, color = "red") #base mod p-value
 
 CPsens_grid<-plot_grid(CPi_sens.p,CPi_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
#ggsave2("C:/Users/robbi/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/CPi_sens.pdf", CPsens_grid, width = 7.8, height = 9.1, dpi = 600)
```

# NP  models
```{r}
#1. create list of time series to delete
series_remove <- det_loc_cnp|>filter(!is.na(NP_ratio)&!is.na(initial_NP))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()

cl <- parallel::makeCluster(4)
registerDoSNOW(cl)
iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
  gam.i_preds <-  gam(data = data.i, NP_ratio ~  
                     te(Mass_per_loss, initial_NP, m = 2)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "REML", family = Gamma(link = "log"),select = TRUE) 
  

predict_gam(type = "link", gam.i_preds, length_out = 1000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL, initial_NP = c(3,2,1.5,1.0,0.6,0.3)))%>%
  mutate(initial_NP = as_factor(initial_NP))|>
  select(-series_index)|>
  mutate(index = as_factor(i), series_index = as_factor(remove.i))

#print(paste("Completed iteration", i), sep = " ")
}

#loop for predictions
registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
   gam.i_pval <-  gam(data = data.i, NP_ratio ~  
               ti(Mass_per_loss, m = 2) + ti(initial_NP, m = 2)+
                     ti(Mass_per_loss, initial_NP, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re"), 
                   method = "ML", family = Gamma(link = "log"),select = TRUE)  

tidy(gam.i_pval)|>filter(str_detect(term, "Mass_per_loss,"))|>bind_cols(id.i)
}

NPi_sens.p<- ggplot()+
  geom_line(data = gam_preds, aes(x = Mass_per_loss, group = model_iteration, y = exp(fit), color = initial_NP), alpha = 0.2)+
  ylab("N:P Ratio")+
  xlab("Mass Loss (%)")+
  facet_wrap(.~initial_NP, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial NP"))+
   theme_bw()+
    NULL
 NPi_sens.p
 

#pvalue density plot - p-value from base penalized model shown in red

 NPi_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 0.017, color = "red") #base mod p-value
 
 NPsens_grid<-plot_grid(NPi_sens.p,NPi_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
#ggsave2("C:/Users/robbi/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/NPi_sens.pdf", NPsens_grid, width = 7.8, height = 9.1, dpi = 600)
```

#Nmass x PO4 model
```{r N X PO4}

series_remove <- det_loc|>filter(!is.na(N_mass)&!is.na(initial_N)&!is.na(srp_avg))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()

cl <- parallel::makeCluster(17)

iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
registerDoSNOW(cl)

gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc|>filter(series_index != remove.i)
  
  gam.i_preds <- gam(data = data.i, N_mass ~  
                  ti(Mass_per_loss) + ti(initial_N)+
                  ti(Mass_per_loss, initial_N, m = 2)+
                  ti(Mass_per_loss,initial_N, srp_avg, m = 1)+ 
               s(series_index, Mass_per_loss, bs = "re")+s(series_index, bs = "re"), 
                   method = "REML", family = gaussian(link = "inverse"),select = TRUE)

predict_gam(type = "link", gam.i_preds, length_out = 5000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL,Remain_Mass_Category = NULL, initial_N = c(3,2,1.5,1.0,0.6,0.3),srp_avg = c(25,50,100)))%>%
   mutate(srp_avg = as_factor(srp_avg), initial_N = as_factor(initial_N))%>%
  select(-series_index)|>
  mutate(model_iteration = i, series_index = as_factor(remove.i))
}

registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc|>filter(series_index != remove.i)
    gam.i_pvals <-  gam(data = det_loc, N_mass ~  
                  ti(Mass_per_loss) + ti(initial_N)+
                  ti(Mass_per_loss, initial_N, m = 2)+
                  ti(Mass_per_loss,initial_N, srp_avg, m = 1)+ 
               s(series_index, Mass_per_loss, bs = "re")+s(series_index, bs = "re"), 
                   method = "ML", family = gaussian(link = "inverse"),select = TRUE)

    tidy(gam.i_pvals)|>filter(str_detect(term, "Mass_per_loss,initial_N,"))|>bind_cols(id.i)
}




 Ni_srp_sens.p<- ggplot(data = gam_preds)+
  geom_line(aes(x = Mass_per_loss, y = 1/fit, color = initial_N, group = series_index), alpha = 0.2)+
  ylab("N mass")+
  xlab("Mass Loss (%)")+
  facet_grid(initial_N~srp_avg, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial N (%)"))+
   theme_bw()+
    NULL
 Ni_srp_sens.p
 

  Ni_srp_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 2e-16, color = "red") #base mod p-value
 
 Ni_srpsens_grid<-plot_grid(Ni_srp_sens.p,Ni_srp_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
ggsave2("C:/Users/Caleb_Robbins/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/Ni_po4_sens.pdf", Ni_srpsens_grid, width = 7.8, height = 9.1, dpi = 600)

```
#CnxTemp Models
```{r}
#1. create list of time series to delete
series_remove <- det_loc_cnp|>filter(!is.na(CN_ratio)&!is.na(initial_CN)&!is.na(Temperature_C_avg))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()
series_remove <- series_remove[1:4]

cl <- parallel::makeCluster(4)

iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
registerDoSNOW(cl)
gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
  
  gam.i_preds <- gam(data = data.i, CN_ratio ~  
                  ti(Mass_per_loss) + ti(initial_CN)+
                  ti(Mass_per_loss, initial_CN)+
               ti(Mass_per_loss,initial_CN, Temperature_C_avg, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re")+ s(series_index, bs = "re"), 
                   method = "REML", family = Gamma(link = "log"),select = TRUE) 

predict_gam(type = "link", gam.i_preds, length_out = 1000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL,Remain_Mass_Category = NULL, initial_CN = c(140,100,70,50,40,25),Temperature_C_avg = c(7.5,10,15,20)))%>%
   mutate(Temperature_C_avg = as_factor(Temperature_C_avg), initial_CN = as_factor(initial_CN))|>
  select(-series_index)|>
  mutate(model_iteration = i, series_index = as_factor(remove.i))
}

registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
    gam.i_pvals <-  gam(data = data.i, CN_ratio ~  
                  ti(Mass_per_loss) + ti(initial_CN)+
                  ti(Mass_per_loss, initial_CN)+
               ti(Mass_per_loss,initial_CN, Temperature_C_avg, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re")+ s(series_index, bs = "re"), 
                   method = "ML", family = Gamma(link = "log"),select = TRUE)  

  tidy(gam.i_pvals)|>filter(str_detect(term, "Mass_per_loss,initial_CN,"))|>bind_cols(id.i)
}



CN_Temp_sens.p<- ggplot(data = gam_preds)+
  geom_line(aes(x = Mass_per_loss, y = exp(fit), color = initial_CN, group = series_index), alpha = 0.2)+
  ylab("C:N Ratio")+
  xlab("Mass Loss (%)")+
  facet_grid(initial_CN~Temperature_C_avg, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial CN"))+
   theme_bw()+
    NULL
 CN_Temp_sens.p


#pvalue density plot - p-value from base penalized model shown in red

 CN_Temp_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 2e-16, color = "red") #base mod p-value
 
 CN_Tempsens_grid<-plot_grid(CN_Temp_sens.p,CN_Temp_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
#ggsave2("C:/Users/caleb/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/CN_Temp_sens.pdf", CN_Tempsens_grid, width = 7.8, height = 9.1, dpi = 600)

```

```{r CN X NO3}

series_remove <- det_loc_cnp|>filter(!is.na(CN_ratio)&!is.na(initial_CN)&!is.na(no3_avg))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()

cl <- parallel::makeCluster(17)

iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
registerDoSNOW(cl)
gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
  
  gam.i_preds <- gam(data = data.i, CN_ratio ~  
                  ti(Mass_per_loss) + ti(initial_CN)+
                  ti(Mass_per_loss, initial_CN)+
               ti(Mass_per_loss,initial_CN, no3_avg, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re")+ s(series_index, bs = "re"), 
                   method = "REML", family = Gamma(link = "log"),select = TRUE) 

predict_gam(type = "link", gam.i_preds, length_out = 5000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL,Remain_Mass_Category = NULL, initial_CN = c(140,100,70,50,40,25),no3_avg = c(100,400,1750)))%>%
   mutate(no3_avg = as_factor(no3_avg), initial_CN = as_factor(initial_CN))%>%
  select(-series_index)|>
  mutate(model_iteration = i, series_index = as_factor(remove.i))
}

registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
    gam.i_pvals <-  gam(data = data.i, CN_ratio ~  
                  ti(Mass_per_loss) + ti(initial_CN)+
                  ti(Mass_per_loss, initial_CN)+
               ti(Mass_per_loss,initial_CN, no3_avg, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re")+ s(series_index, bs = "re"), 
                   method = "ML", family = Gamma(link = "log"),select = TRUE)  

    tidy(gam.i_pvals)|>filter(str_detect(term, "Mass_per_loss,initial_CN,"))|>bind_cols(id.i)
}




 CN_no3_sens.p<- ggplot(data = gam_preds)+
  geom_line(aes(x = Mass_per_loss, y = exp(fit), color = initial_CN, group = series_index), alpha = 0.2)+
  ylab("C:N Ratio")+
  xlab("Mass Loss (%)")+
  facet_grid(initial_CN~no3_avg, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial CN"))+
   theme_bw()+
    NULL
 CN_no3_sens.p
 

  CN_no3_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 2e-16, color = "red") #base mod p-value
 
 CN_no3sens_grid<-plot_grid(CN_no3_sens.p,CN_no3_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
ggsave2("C:/Users/Caleb_Robbins/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/CN_no3_sens.pdf", CN_no3sens_grid, width = 7.8, height = 9.1, dpi = 600)

```

```{r CN X PO4}

series_remove <- det_loc_cnp|>filter(!is.na(CN_ratio)&!is.na(initial_CN)&!is.na(srp_avg))|>distinct(series_index)|>
  mutate(series_index = as.numeric(series_index))|>pull()

cl <- parallel::makeCluster(17)

iterations <- length(series_remove)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
registerDoSNOW(cl)
gam_preds<-foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
#fit gam for plotting predictions
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
  
  gam.i_preds <- gam(data = data.i, CN_ratio ~  
                  ti(Mass_per_loss) + ti(initial_CN)+
                  ti(Mass_per_loss, initial_CN)+
               ti(Mass_per_loss,initial_CN, srp_avg, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re")+ s(series_index, bs = "re"), 
                   method = "REML", family = Gamma(link = "log"),select = TRUE) 

predict_gam(type = "link", gam.i_preds, length_out = 5000,  exclude_terms = c("s(series_index)", "s(series_index, Mass_per_loss)"), values = list(series_index = NULL,Remain_Mass_Category = NULL, initial_CN = c(140,100,70,50,40,25),srp_avg = c(25,50,100)))%>%
   mutate(srp_avg = as_factor(srp_avg), initial_CN = as_factor(initial_CN))%>%
  select(-series_index)|>
  mutate(model_iteration = i, series_index = as_factor(remove.i))
}

registerDoSNOW(cl)
gam_sums <- foreach(i = 1:length(series_remove),.packages = c("tidyverse", "mgcv", "broom", "tidymv"), .combine = rbind, .options.snow = opts,.inorder = TRUE) %dopar% {
  
  remove.i <- series_remove[i]
  id.i <- det_loc_cnp|>filter(series_index == remove.i)|>select(First_Author, Publication_Title, Publication_Year, Journal, series_index)|>slice_head(n=1)
  
  data.i <- det_loc_cnp|>filter(series_index != remove.i)
    gam.i_pvals <-  gam(data = data.i, CN_ratio ~  
                  ti(Mass_per_loss) + ti(initial_CN)+
                  ti(Mass_per_loss, initial_CN)+
               ti(Mass_per_loss,initial_CN, srp_avg, m = 1)+
                        s(series_index, Mass_per_loss, bs = "re")+ s(series_index, bs = "re"), 
                   method = "ML", family = Gamma(link = "log"),select = TRUE)  

    tidy(gam.i_pvals)|>filter(str_detect(term, "Mass_per_loss,initial_CN,"))|>bind_cols(id.i)
}




 CN_srp_sens.p<- ggplot(data = gam_preds)+
  geom_line(aes(x = Mass_per_loss, y = exp(fit), color = initial_CN, group = series_index), alpha = 0.2)+
  ylab("C:N Ratio")+
  xlab("Mass Loss (%)")+
  facet_grid(initial_CN~srp_avg, scales = "free")+
  scale_color_brewer(palette = "Dark2")+
  guides(color=guide_legend(title="Initial CN"))+
   theme_bw()+
    NULL
 CN_srp_sens.p
 

  CN_srp_pvals.p<-ggplot(data = gam_sums, aes(x = p.value))+geom_density()+geom_vline(xintercept = 2e-16, color = "red") #base mod p-value
 
 CN_srpsens_grid<-plot_grid(CN_srp_sens.p,CN_srp_pvals.p, nrow = 2, labels = "AUTO", label_size = 20)
ggsave2("C:/Users/Caleb_Robbins/Dropbox/Detrital Nutrients Synth/Manuscript Dev/Temporal Trends ms/Figures/Sensitivity Figures/CN_po4_sens.pdf", CN_srpsens_grid, width = 7.8, height = 9.1, dpi = 600)

```

